name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: FirstBuildJob
    runs-on: ubuntu-latest 
    steps:
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            add_path("/usr/local/test")
            set_env("HELLO", "WORLD")
            group("Messages")
            print("Sending a message")
            warning("There might be an issue")
            end_group()
