name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: FirstBuildJob
    runs-on: ubuntu-latest 
    steps:
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            set_env("HELLO", "WORLD")
            
            print(HELLO)
            
