name: Run Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: FirstBuildJob
    runs-on: ubuntu-latest 
    steps:
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |            
            def set_env(name, value):
              with open(os.getenv("GITHUB_ENV"), "a") as env:
                print(f"{name}={_escape_data(value)}", file=env)
