name: Run Script

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    name: FirstBuildJob
    runs-on: ubuntu-latest 
    steps:
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |            
              print(os.getenv("GITHUB_REF_NAME", " not found"))
