name: workflow-tags
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  job-tags:
    runs-on: ubuntu-latest
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1

    - name: Branch name
      id: branch_name
      run:
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        
    - name: Build base image
      run:
        echo $SOURCE_TAG
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    
  build:
    name: FirstBuildJob
    runs-on: ubuntu-latest 
    steps:
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |            
            def set_env(name, value):
            with open(os.getenv("SOURCE_TAG"), ${{ steps.branch_name.outputs.SOURCE_TAG }}) as env:
            print(f"{name}={_escape_data(value)}", file=env)
