name: workflow-tags
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  job-tags:
    runs-on: ubuntu-latest
    steps:
    - name: "step-checkout"
      uses: actions/checkout@v1

    - name: Branch name
      id: branch_name
      run:
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        
    - name: Build base image
      uses: actions/setup-python@v2
      with:
          script: |
            import os
            version = os.environ.get("SOURCE_TAG")
            print(version) 
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
    
  job-use-tag:
    runs-on: ubuntu-latest
    steps:
    - name: "use the tag in script"
      run :
        echo $SOURCE_TAG
        #with:
          #script: |
            #import os
            #print("It's stated")
            #version = os.environ.get("SOURCE_TAG")
            #if not version:
            #  raise RuntimeError("SOURCE_TAG env var is not set!")
            #print("All good! we found our env var")
